name: subabase_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  form_helpers:
    git:
      url: https://github.com/MohamedAboElM3aTy/form_helpers
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

# ? dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
